Landing page
kgajriaAgarwal/BlitheEcommerce pull request #3
Opened 2022-02-10 14:47 UTC by kgajriaAgarwal

Created landing page. Kindly review it and let me know what do you think about it !

2022-02-10 15:35 UTC, Ankur9669 requested changes
I think you have put all your code in the same branch, so first i would request you to solve this issue.

For now i have only reviewed you UI.


![image](https://user-images.githubusercontent.com/65125998/153440271-bca84072-68b8-4533-93d8-8f0be23b2d5e.png)
1. Adding a little padding beetween the sections would make it look good.

![image](https://user-images.githubusercontent.com/65125998/153440472-51c7d414-a733-456e-9cb6-21daf94eb628.png)

1. The image is blurry is this intensional?

![image](https://user-images.githubusercontent.com/65125998/153440657-3b9efc57-0176-419b-9b95-e8e7e04a3830.png)
1. Can add a little padding inside the card.

2022-02-10 15:35 UTC, Ankur9669 commented on Authentication/Login/Login.css
> +
Why login.css in homepage🤔

2022-02-11 09:20 UTC, Naman-Saxena1 requested changes
I agree with Ankur, you should segregate PRs and resolve this branch issue, as this PR has code for other things as well. When Neogcamp team will look into your project and PRs for assessment, it can confuse them.

I have suggested UI changes that need to be resolved for better user experience.

![Screenshot 2022-02-11 142735](https://user-images.githubusercontent.com/90456667/153564189-242e21cc-8e17-48b9-8af1-b5bc717a62f5.png)
Your image is getting blurred because its intrinsic value is less than rendered dimensions.

 
![Capture](https://user-images.githubusercontent.com/90456667/153564481-1972b549-c269-4e11-add5-0344ff6efa97.PNG)
I believe these will be clickable in the future, so it is semantically better to create them as buttons rather than divs.

![Capture2](https://user-images.githubusercontent.com/90456667/153564689-40b52701-19a1-429d-ab63-69b79d099264.PNG)
Text is overflowing and overlapping on other elements.



![Capture3](https://user-images.githubusercontent.com/90456667/153564910-7e4e1276-b586-4ede-9cea-97f441d9bf3d.PNG)
There should be consistency in their sizes and also add some on hover effect and cursor: pointer. Also since cart will be button, it is better to use button tag with Font Awesome icons in it than divs containing img.

  
![Screenshot 2022-02-11 144643](https://user-images.githubusercontent.com/90456667/153565516-eb5037a7-d38c-44be-a274-854e307bf4ab.png)
![Screenshot 2022-02-11 144718](https://user-images.githubusercontent.com/90456667/153565597-4876d69e-f3a3-4193-9384-a11e7fb8352c.png)
When I hover over card buttons, card height increases because of border getting added to button on hover, that should be fixed as it does not give good user experience.

2022-02-11 09:41 UTC, Ankur9669 requested changes
![image](https://user-images.githubusercontent.com/65125998/153568409-c9952938-cc09-478e-b6f5-8bf0c86baf6e.png)
Could have more margin, and equal top and bottom margin.


![image](https://user-images.githubusercontent.com/65125998/153568508-cdb6631d-828a-4fb2-ba11-25fbbf448056.png)

This cards container could have more top and bottom padding.

![image](https://user-images.githubusercontent.com/65125998/153568584-30d63411-2798-4bde-bc3f-9ed422a2dcd6.png)

1. The card lorem ispum text is very small and difficult to read, so you can increase the font-size.
2. And also there could be some margin beetwen the loremispum and the heading of the card

![image](https://user-images.githubusercontent.com/65125998/153568831-90b0d454-877f-4137-930d-0d0ca6e779ee.png)

These could have more top and bottom margins.

![image](https://user-images.githubusercontent.com/65125998/153568995-1f16694f-fd2d-4110-927e-52849f091c84.png)

The badge is not properly aligned with the heading text

![image](https://user-images.githubusercontent.com/65125998/153569082-47df1f55-3866-4426-bdb3-0617f3994183.png)

The 299 price is not centered vertically

![image](https://user-images.githubusercontent.com/65125998/153569141-d1e677ba-15f7-412e-89f9-646c93997d83.png)

Margin is inconsistent in bottom it is more but on top it is less

2022-02-11 09:41 UTC, Ankur9669 commented on Common.css
> +    justify-content: center;
Could remove commented code and could convert the px into rem if you want

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +}
Dont use camel casing in css

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +	height: 65vh;
Same you have used camel casing here

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +
Why the use of !important?? This could cause issues

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +    justify-content: center;
By default flex-wrap is nowrap only so you can remove it

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +    overflow: scroll;
Same you can remove flex-wrap

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +	padding-bottom: 1rem;
If possible dont use id's and in Testimonials "T" should be small

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +    padding-top: 2rem;
Can remove nowrap

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.css
> +	border-radius: 50%;
Could use rems

2022-02-11 09:41 UTC, Ankur9669 commented on LandingPage/LandingPage.js
> +}
Could use es6 here

2022-02-13 15:32 UTC, kgajriaAgarwal commented on Common.css
> +    justify-content: center;
removed

2022-02-13 16:06 UTC, kgajriaAgarwal commented on LandingPage/LandingPage.css
> +}
removed came casing

2022-02-13 16:10 UTC, kgajriaAgarwal commented on LandingPage/LandingPage.css
> +	height: 65vh;
removed came casing

2022-02-13 17:12 UTC, kgajriaAgarwal commented
done changes acc to the above comments.

2022-02-20 18:28 UTC, closed without merging